Merge pull request #2 from dof1985/cwatm_wq
dof1985/CWatM pull request #4
Opened 2023-01-19 14:57 UTC by f-s-d

Cwatm wq

2023-01-31 11:50 UTC, dof1985 requested changes
See comments in code.

Overall it looks good. There is just one main change I wish you implement - can you think of another name instead erosed? I find it is not intuitive enough, and would not be easily to interpret within the code. 

I am not sure about the change in gitignore - what is it about?

2023-01-31 11:50 UTC, dof1985 commented on cwatm/hydrological_modules/water_quality/erosed.py
> +class waterquality_erosed(object):
What does 'erosed' stand for?

2023-01-31 11:50 UTC, dof1985 commented on cwatm/hydrological_modules/water_quality/erosed.py
> +        print('erosed init')
Choos one type on quotation marks for strings, either ' or "., see lines 47 and 53 for example

2023-01-31 11:50 UTC, dof1985 commented on cwatm/hydrological_modules/water_quality/waterquality_main.py
> +        self.erosed = waterquality_erosed(model)
Here again about erosed - I would try to think on something a bit more intuitive to improve code readability. 
Maybe sediment?

2023-01-31 11:50 UTC, dof1985 commented on cwatm/hydrological_modules/water_quality/waterquality_main.py
> +        if self.var.includeWaterQuality:
It is not necessarily the place to run dynamic. I guess you might want to sync it with the soil module

2023-02-02 11:03 UTC, f-s-d commented on cwatm/hydrological_modules/water_quality/erosed.py
> +class waterquality_erosed(object):
EROsion SEDiment

2023-02-02 11:17 UTC, dof1985 approved these changes
You have handled the conflicts very well

2023-02-02 11:18 UTC, merged